// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'brand': string;
  'brand-logo': string;
  'brand-name': string;
  'brandLogo': string;
  'brandName': string;
  'navbar-container': string;
  'navbar-item': string;
  'navbar-links': string;
  'navbarContainer': string;
  'navbarItem': string;
  'navbarLinks': string;
}
export const cssExports: CssExports;
export default cssExports;
